// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhzvZf3XrMEsxHVQ3eHKZs8y886Ge1ZWE',
    appId: '1:772517225552:web:63d47daa075fe4ffed1d55',
    messagingSenderId: '772517225552',
    projectId: 'vocabularylearning-19f75',
    authDomain: 'vocabularylearning-19f75.firebaseapp.com',
    storageBucket: 'vocabularylearning-19f75.firebasestorage.app',
    measurementId: 'G-LYPM172N9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6prilkMMgHmvwy5Wu4n_05MYgh8wOyNE',
    appId: '1:772517225552:android:b5024853a3ba9996ed1d55',
    messagingSenderId: '772517225552',
    projectId: 'vocabularylearning-19f75',
    storageBucket: 'vocabularylearning-19f75.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhzvZf3XrMEsxHVQ3eHKZs8y886Ge1ZWE',
    appId: '1:772517225552:web:958e91e3e56412aeed1d55',
    messagingSenderId: '772517225552',
    projectId: 'vocabularylearning-19f75',
    authDomain: 'vocabularylearning-19f75.firebaseapp.com',
    storageBucket: 'vocabularylearning-19f75.firebasestorage.app',
    measurementId: 'G-4QEPZHSY78',
  );
}
